"""initial_schema

Revision ID: c37ee143411a
Revises: 
Create Date: 2026-02-23 19:46:13.765911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c37ee143411a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('ein', sa.String(length=10), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('ntee_code', sa.String(length=10), nullable=True),
    sa.Column('ruling_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ein')
    )
    op.create_index('idx_org_ein', 'organizations', ['ein'], unique=False)
    op.create_index('idx_org_name_trgm', 'organizations', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_org_ntee', 'organizations', ['ntee_code'], unique=False)
    op.create_index('idx_org_state', 'organizations', ['state'], unique=False)
    op.create_table('users',
    sa.Column('clerk_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id')
    )
    op.create_table('filings',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('object_id', sa.String(length=50), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('filing_type', sa.String(length=10), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('total_revenue', sa.BigInteger(), nullable=True),
    sa.Column('total_expenses', sa.BigInteger(), nullable=True),
    sa.Column('net_assets', sa.BigInteger(), nullable=True),
    sa.Column('contributions_and_grants', sa.BigInteger(), nullable=True),
    sa.Column('program_service_revenue', sa.BigInteger(), nullable=True),
    sa.Column('investment_income', sa.BigInteger(), nullable=True),
    sa.Column('program_expenses', sa.BigInteger(), nullable=True),
    sa.Column('management_expenses', sa.BigInteger(), nullable=True),
    sa.Column('fundraising_expenses', sa.BigInteger(), nullable=True),
    sa.Column('num_employees', sa.Integer(), nullable=True),
    sa.Column('num_volunteers', sa.Integer(), nullable=True),
    sa.Column('mission_description', sa.Text(), nullable=True),
    sa.Column('raw_xml_url', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id')
    )
    op.create_index('idx_filing_org', 'filings', ['organization_id'], unique=False)
    op.create_index('idx_filing_type', 'filings', ['filing_type'], unique=False)
    op.create_index('idx_filing_year', 'filings', ['tax_year'], unique=False)
    op.create_table('saved_searches',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('clerk_org_id', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_org_id')
    )
    op.create_table('usage_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_user_date', 'usage_events', ['user_id', 'created_at'], unique=False)
    op.create_table('filing_grants',
    sa.Column('filing_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_name', sa.Text(), nullable=False),
    sa.Column('recipient_ein', sa.String(length=10), nullable=True),
    sa.Column('recipient_city', sa.Text(), nullable=True),
    sa.Column('recipient_state', sa.String(length=2), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grants_filing', 'filing_grants', ['filing_id'], unique=False)
    op.create_table('filing_people',
    sa.Column('filing_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('compensation', sa.BigInteger(), nullable=True),
    sa.Column('is_officer', sa.Boolean(), nullable=False),
    sa.Column('is_director', sa.Boolean(), nullable=False),
    sa.Column('is_key_employee', sa.Boolean(), nullable=False),
    sa.Column('is_highest_compensated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_people_filing', 'filing_people', ['filing_id'], unique=False)
    op.create_table('org_scores',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('filing_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('revenue_diversity_score', sa.Integer(), nullable=True),
    sa.Column('operating_reserves_score', sa.Integer(), nullable=True),
    sa.Column('fundraising_efficiency_score', sa.Integer(), nullable=True),
    sa.Column('program_expense_ratio_score', sa.Integer(), nullable=True),
    sa.Column('revenue_growth_score', sa.Integer(), nullable=True),
    sa.Column('working_capital_score', sa.Integer(), nullable=True),
    sa.Column('peer_percentile', sa.Integer(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_summaries',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('filing_id', sa.Uuid(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id')
    )
    op.create_table('watchlists',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_items',
    sa.Column('watchlist_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_table('watchlists')
    op.drop_table('team_members')
    op.drop_table('org_summaries')
    op.drop_table('org_scores')
    op.drop_index('idx_people_filing', table_name='filing_people')
    op.drop_table('filing_people')
    op.drop_index('idx_grants_filing', table_name='filing_grants')
    op.drop_table('filing_grants')
    op.drop_index('idx_usage_user_date', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('teams')
    op.drop_table('saved_searches')
    op.drop_index('idx_filing_year', table_name='filings')
    op.drop_index('idx_filing_type', table_name='filings')
    op.drop_index('idx_filing_org', table_name='filings')
    op.drop_table('filings')
    op.drop_table('users')
    op.drop_index('idx_org_state', table_name='organizations')
    op.drop_index('idx_org_ntee', table_name='organizations')
    op.drop_index('idx_org_name_trgm', table_name='organizations', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_org_ein', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
    op.execute('DROP EXTENSION IF EXISTS pg_trgm')
